package com.pojo;

// Generated Apr 15, 2020 1:39:20 PM by Hibernate Tools 3.4.0.CR1

/**
 * File generated by hbm2java
 */
public class File implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private String file;
	private Integer uid;

	public File() {
	}

	public File(String name, String description, String file, Integer uid) {
		this.name = name;
		this.description = description;
		this.file = file;
		this.uid = uid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getFile() {
		return this.file;
	}

	public void setFile(String file) {
		this.file = file;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

}
